In [1]:
# Define a string
my_string = "Hello, World!"

# Print the string
print("Original string:", my_string)

# Length of the string
print("Length of string:", len(my_string))

# Accessing characters in the string
print("First character:", my_string[0])
print("Last character:", my_string[-1])
print("Substring from index 7 to end:", my_string[7:])

# Concatenation
new_string = my_string + " Welcome!"
print("Concatenated string:", new_string)

# String repetition
repeated_string = my_string * 3
print("String repetition:", repeated_string)

# String formatting
name = "Alice"
age = 30
formatted_string = "My name is {} and I am {} years old.".format(name, age)
print("Formatted string:", formatted_string)

# String methods
print("Uppercase:", my_string.upper())
print("Lowercase:", my_string.lower())
print("Is the string alphanumeric?", my_string.isalnum())
print("Index of 'World':", my_string.index("World"))
print("Replacing 'Hello' with 'Hi':", my_string.replace("Hello", "Hi"))

# Splitting the string
split_string = "apple,banana,orange"
print("Split string:", split_string.split(","))

# Stripping whitespace
whitespace_string = "   Hello, World!   "
print("Stripped string:", whitespace_string.strip())

# Check if a string starts or ends with a certain substring
print("Starts with 'Hello'?", my_string.startswith("Hello"))
print("Ends with 'World'?", my_string.endswith("World!"))


Original string: Hello, World!
Length of string: 13
First character: H
Last character: !
Substring from index 7 to end: World!
Concatenated string: Hello, World! Welcome!
String repetition: Hello, World!Hello, World!Hello, World!
Formatted string: My name is Alice and I am 30 years old.
Uppercase: HELLO, WORLD!
Lowercase: hello, world!
Is the string alphanumeric? False
Index of 'World': 7
Replacing 'Hello' with 'Hi': Hi, World!
Split string: ['apple', 'banana', 'orange']
Stripped string: Hello, World!
Starts with 'Hello'? True
Ends with 'World'? True


In [2]:
# Integer
integer_var = 10
print("Integer variable:", integer_var)
print("Type:", type(integer_var))

# Float
float_var = 3.14
print("Float variable:", float_var)
print("Type:", type(float_var))

# String
string_var = "Hello, World!"
print("String variable:", string_var)
print("Type:", type(string_var))

# Boolean
boolean_var = True
print("Boolean variable:", boolean_var)
print("Type:", type(boolean_var))

# List
list_var = [1, 2, 3, 4, 5]
print("List variable:", list_var)
print("Type:", type(list_var))

# Tuple
tuple_var = (1, 2, 3, 4, 5)
print("Tuple variable:", tuple_var)
print("Type:", type(tuple_var))

# Dictionary
dict_var = {"name": "Alice", "age": 30}
print("Dictionary variable:", dict_var)
print("Type:", type(dict_var))

# Set
set_var = {1, 2, 3, 4, 5}
print("Set variable:", set_var)
print("Type:", type(set_var))

# None
none_var = None
print("None variable:", none_var)
print("Type:", type(none_var))


Integer variable: 10
Type: <class 'int'>
Float variable: 3.14
Type: <class 'float'>
String variable: Hello, World!
Type: <class 'str'>
Boolean variable: True
Type: <class 'bool'>
List variable: [1, 2, 3, 4, 5]
Type: <class 'list'>
Tuple variable: (1, 2, 3, 4, 5)
Type: <class 'tuple'>
Dictionary variable: {'name': 'Alice', 'age': 30}
Type: <class 'dict'>
Set variable: {1, 2, 3, 4, 5}
Type: <class 'set'>
None variable: None
Type: <class 'NoneType'>


In [3]:
# For loop
print("For loop:")
for i in range(5):
    print(i, end=" ")  # Print numbers from 0 to 4
print()  # New line

# While loop
print("\nWhile loop:")
count = 0
while count < 5:
    print(count, end=" ")  # Print numbers from 0 to 4
    count += 1
print()  # New line

# Nested loops
print("\nNested loops:")
for i in range(3):
    for j in range(2):
        print(i, j)  # Print combinations of i and j


For loop:
0 1 2 3 4 

While loop:
0 1 2 3 4 

Nested loops:
0 0
0 1
1 0
1 1
2 0
2 1


In [4]:
# Define a variable
x = 10

# If-else condition
if x > 10:
    print("x is greater than 10")
else:
    print("x is not greater than 10")

# If-elif-else condition
if x > 10:
    print("x is greater than 10")
elif x < 10:
    print("x is less than 10")
else:
    print("x is equal to 10")


x is not greater than 10
x is equal to 10


In [5]:
# Define a function
def greet():
    print("Hello, World!")

# Call the function
greet()

# Define a function with parameters
def greet_person(name):
    print("Hello,", name)

# Call the function with an argument
greet_person("Alice")

# Define a function with a return value
def add_numbers(a, b):
    return a + b

# Call the function and store the result
result = add_numbers(5, 3)
print("Result of addition:", result)

# Define a function with default parameter value
def greet_with_default(name="World"):
    print("Hello,", name)

# Call the function without providing an argument
greet_with_default()

# Call the function with an argument
greet_with_default("Bob")


Hello, World!
Hello, Alice
Result of addition: 8
Hello, World
Hello, Bob


In [7]:
# Define a class
class Car:
    # Class attribute
    wheels = 4
    
    # Constructor (initializer) method
    def __init__(self, make, model, year):
        # Instance attributes
        self.make = make
        self.model = model
        self.year = year
    
    # Instance method
    def info(self):
        return f"{self.year} {self.make} {self.model} with {self.wheels} wheels."

# Create instances of the class
car1 = Car("Toyota", "Crown", 2024)
car2 = Car("Honda", "Nsx", 2023)

# Access instance attributes
print("Car 1:", car1.info())
print("Car 2:", car2.info())

# Access class attribute
print("Number of wheels for Car 1:", car1.wheels)
print("Number of wheels for Car 2:", car2.wheels)


Car 1: 2024 Toyota Crown with 4 wheels.
Car 2: 2023 Honda Nsx with 4 wheels.
Number of wheels for Car 1: 4
Number of wheels for Car 2: 4


In [10]:
# Import NumPy library
import numpy as np

# Create a 1D NumPy array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr1)

# Create a 2D NumPy array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:")
print(arr2)

# Accessing elements in arrays
print("\nAccessing elements:")
print("Element at index 2 in arr1:", arr1[2])
print("Element at index (1, 2) in arr2:", arr2[1, 2])

# Array attributes
print("\nArray attributes:")
print("Shape of arr1:", arr1.shape)
print("Shape of arr2:", arr2.shape)
print("Number of dimensions in arr1:", arr1.ndim)
print("Number of dimensions in arr2:", arr2.ndim)
print("Data type of arr1 elements:", arr1.dtype)
print("Data type of arr2 elements:", arr2.dtype)

# Array operations
print("\nArray operations:")
print("Sum of elements in arr1:", np.sum(arr1))
print("Mean of elements in arr2:", np.mean(arr2))
print("Maximum element in arr1:", np.max(arr1))
print("Minimum element in arr2:", np.min(arr2))

# Array manipulation
print("\nArray manipulation:")
print("Reshaping arr1 to (5, 1):", arr1.reshape(5, 1))
print("Transposing arr2:", arr2.T)


1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]]

Accessing elements:
Element at index 2 in arr1: 3
Element at index (1, 2) in arr2: 6

Array attributes:
Shape of arr1: (5,)
Shape of arr2: (2, 3)
Number of dimensions in arr1: 1
Number of dimensions in arr2: 2
Data type of arr1 elements: int32
Data type of arr2 elements: int32

Array operations:
Sum of elements in arr1: 15
Mean of elements in arr2: 3.5
Maximum element in arr1: 5
Minimum element in arr2: 1

Array manipulation:
Reshaping arr1 to (5, 1): [[1]
 [2]
 [3]
 [4]
 [5]]
Transposing arr2: [[1 4]
 [2 5]
 [3 6]]


In [14]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv(r'C:\Users\khatr\OneDrive\Desktop\Book1.csv')

# Print the DataFrame
print("Contents of the CSV file:")
print(df)


Contents of the CSV file:
     MONTHS  SALES   EXPENSES   PROFITS  Unnamed: 4  Unnamed: 5 Unnamed: 6
0       JAN   150.0      125.0     25.0         NaN         NaN        NaN
1       FEB   175.0      150.0     25.0         NaN         NaN        NaN
2       MAR   225.0      210.0     15.0         NaN         NaN        NaN
3       NaN     NaN        NaN      NaN         NaN         NaN           
4    TOTALS   550.0      485.0     65.0         NaN         NaN        NaN
5       NaN     NaN        NaN      NaN         NaN         NaN        NaN
6  APR PROJ   187.5      167.5     20.0         NaN         NaN        NaN
